version: '3.8'

services:
  app:
    build: .
    container_name: telemedicine-api
    ports:
      - "8080:8080"
    environment:
      - DB_PATH=/root/data/telemedicine.db
    volumes:
      - ./data:/root/data
    restart: always